//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ClinicEntities : DbContext
    {
        public ClinicEntities()
            : base("name=ClinicEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Disease> Diseases { get; set; }
        public virtual DbSet<Patient> Patients { get; set; }
        public virtual DbSet<DiseaseDetail> DiseaseDetails { get; set; }
        public virtual DbSet<HealthcareFacilityDetail> HealthcareFacilityDetails { get; set; }
        public virtual DbSet<MedicineDetail> MedicineDetails { get; set; }
        public virtual DbSet<HealthcareFacility> HealthcareFacilities { get; set; }
        public virtual DbSet<TreatmentRequest> TreatmentRequests { get; set; }
        public virtual DbSet<Payment> Payments { get; set; }
        public virtual DbSet<Medicine> Medicines { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
