//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiseaseDetail
    {
        public long TreatmentRequestId { get; set; }
        public long DiseaseId { get; set; }
        public System.DateTime TreatmentDate { get; set; }
        public string TreatmentMethod { get; set; }
    
        public virtual Disease Disease { get; set; }
        public virtual TreatmentRequest TreatmentRequest { get; set; }
    }
}
