//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public long PaymentId { get; set; }
        public long TreatmentRequestId { get; set; }
        public System.DateTime PayDate { get; set; }
        public decimal AmountMoney { get; set; }
        public string Note { get; set; }
    
        public virtual TreatmentRequest TreatmentRequest { get; set; }
    }
}
